baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blamoo.github.io" # the base hostname & protocol for your site
gems:
    - jekyll-sitemap
collections:
    posts:
        output: true
        permalink: "/:categories/:title:output_ext"
include:
    - ".well-known"
excerpt_separator: "<!-- more -->"
